gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
paginate: 10

name: qwertyuiop.ninja
description: Good with a keyboard and fluent in gibberish
author:
  name: Jamie
  email: me@astro73.com
  uri: http://astro73.com/
defaults:
- values:
    articleclass: text

twitter:
  username: QwertyuiopNinja
facebook:
  publisher: https://www.facebook.com/qwertyuiopninja/
author:
  twitter: astronouth7303
social:
  links:
    - https://www.facebook.com/qwertyuiopninja/
    - https://plus.google.com/+QwertyuiopNinja
    - https://twitter.com/QwertyuiopNinja
logo: /assets/avatar.128.png